package com.transformedge.teewb.request;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import java.util.HashMap;

/**
 * Created by chandrasekarramaswamy on 15/07/18.
 */
@JsonRootName(value = "OutputResponse")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CancelOutputResponse {
    private HashMap<String, String> columns;

    @JsonCreator
    public CancelOutputResponse() {
    }

    @JsonAnyGetter
    public HashMap<String, String> getColumns() {
        return columns;
    }

    public void setColumns(HashMap<String, String> columns) {
        this.columns = columns;
    }

    public String getColumnValue(String key) {
        return columns.get(key);
    }

    @Override
    public String toString() {
        return columns.toString();
    }

    @JsonAnySetter
    public void putColumn(String key, String value) {
        if (columns == null) columns = new HashMap<>();
        columns.put(key, value);
    }

    public boolean isSuccess() {
        return (columns.get("ewayBillNo") != null || columns.get("cancelDate") != null);
    }

    public String toJSON() {
        ObjectMapper mapper  = new ObjectMapper();
        mapper.configure(SerializationFeature.WRAP_ROOT_VALUE, true);
        try {
            return mapper.writeValueAsString(this);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
            return null;
        }
    }

    public static void main(String args[]) throws Exception {
        String json = "{\n" +
                "    \"OutputResponse\": {\n" +
                "        \"errorCodes\": \"312,\",\n" +
                "        \"errorDescription\": \"This eway bill is either not generated by you or cancelled\"\n" +
                "    }\n" +
                "}";
        ObjectMapper mapper  = new ObjectMapper();
        mapper.configure(DeserializationFeature.UNWRAP_ROOT_VALUE, true);
        try {
            CancelOutputResponse cancelOutputResponse = mapper.readValue(json, CancelOutputResponse.class);
            System.out.println("cancel response is: " + cancelOutputResponse);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
    }
}
