server:
  port: 8080
camel:
  springboot:
    name: gstr
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
  
############ QUERIES FOR FETCHING DATA ##################
query-configuration:
  source: CSV


####################### CSV CONFIGURATION #######################
csv-configuration:
  configurations:
    -
      name: saveGstrForDocuments
      inputPath: D:/GST_API_Details/My_Reference/GSTR2_CSV_DATA/save_gstr/data_input
      outputPath: D:/GST_API_Details/My_Reference/GSTR2_CSV_DATA/save_gstr/data_output
      userName:
      password:
      initialDelay: 5000
      consumeDelay: 5000
      tableMetadataConfiguration:
        tables:
          -
            name: gstrTable
            identifierColumn: FIRST_PARTY_PRIMARY_REG_NUM
            columns:
              - TAX_LINE_ID                 
              - TAX_LINE_NUM                 
              - FIRST_PARTY_PRIMARY_REG_NUM  
              - FIRST_PARTY_REG_ID           
              - THIRD_PARTY_REG_NUM         
              - TRX_ID                       
              - TAX_INVOICE_NUMBER          
              - TAX_INVOICE_DATE             
              - TAX_INVOICE_VALUE            
              - TAX_RATE                     
              - TAXABLE_AMT                
              - GRAND_TOT                   
              - CUR_GT                     
              - SGST                        
              - CGST                     
              - IGST                     
              - CESS                    
              - POS                       
              - TAX_TYPE_CODE             
              - ITEM_DESCRIPTION            
              - LOCATION_ID                 
              - FLAG                      
              - INV_TYPE                   
              - REV_CHARGE                 
              - ECOM_OPERATOR               
              - INV_CHECK_SUM_VAL           
              - EXPORT_TYPE                  
              - SHIPPABLE_PORT_CODE          
              - SHIPPABLE_BILL_NO           
              - SHIPPABLE_BILL_DATE         
              - HSN_CODE                   
              - HSN_DESC                  
              - QTY                       
              - UOM                         
              - CPPDR                        
              - NIL_AMOUNT                  
              - EXPT_AMOUNT                  
              - NGSUP_AMOUNT                 
              - ADV_RECEIPT_AMT              
              - ADJUSTMENT_AMOUNT           
              - SUPP_TYPE                  
              - APPLIED_TO_TRX_ID           
              - REQUEST_ID                  
              - ATTRIBUTE1                  
              - ATTRIBUTE2                   
              - ATTRIBUTE3                   
              - ATTRIBUTE4                   
              - ATTRIBUTE5                 
              - ATTRIBUTE6                
              - ATTRIBUTE7                  
              - ATTRIBUTE8                   
              - ATTRIBUTE9                  
              - ATTRIBUTE10                 
              - ATTRIBUTE11                 
              - ATTRIBUTE12                  
              - APPLIED_FROM_TRX_ID         
              - INELIG_ITC_FLAG             
              - ITC_IGST                     
              - ITC_SGST                     
              - ITC_CGST                     
              - ITC_CESS                     
              - RULE_NO                      
              - SERIAL_NUM                   
              - PORT_CODE                    
              - IS_SEZ                       
              - REV_GSTIN                    
              - REV_INV_NUM                  
              - REV_INV_DATE                 
              - REV_INV_VAL                  
              - NOTE_TYPE                    
              - NOTE_NUMBER                  
              - NOTE_DATE                   
              - P_GST                
              - RSN                      
              - ELG                      
              - CHKSUM                     
              - TRX_NUMBER                 
              - TRX_DATE                     
              - EVENT_CLASS_CODE          
              - DOC_TYPE                 
              - TOT_NUM                    
              - CANCEL                      
              - NET_ISSUE                   
              - STATUS                      
              - ELIGIBLE_GSTR1              
              - STATUS_GSTR1                
              - ELIGIBLE_GSTR2              
              - STATUS_GSTR2                
              - PERIOD_NAME                 
              - SOURCE_SECTION              
              - BATCH_ID                     
              - PROCESS_STATUS                              
      validation:
        numericColumns:
          - TAX_LINE_ID                  
          - TAX_LINE_NUM                 
          - FIRST_PARTY_REG_ID           
          - TRX_ID                       
          - TAX_INVOICE_VALUE            
          - TAX_RATE                     
          - TAXABLE_AMT                  
          - GRAND_TOT                    
          - CUR_GT                       
          - SGST                         
          - CGST                         
          - IGST                         
          - CESS                         
          - LOCATION_ID                  
          - QTY                          
          - CPPDR                        
          - NIL_AMOUNT                   
          - EXPT_AMOUNT                  
          - NGSUP_AMOUNT                 
          - ADV_RECEIPT_AMT              
          - ADJUSTMENT_AMOUNT            
          - APPLIED_TO_TRX_ID            
          - REQUEST_ID                   
          - APPLIED_FROM_TRX_ID          
          - ITC_IGST                     
          - ITC_SGST                     
          - ITC_CGST                     
          - ITC_CESS                     
          - RULE_NO                      
          - SERIAL_NUM                   
          - REV_INV_VAL                  
          - TOT_NUM                      
          - BATCH_ID   
      outputColumns:
        - gstin_number
        - gstin_action_type
        - gstin_error_message
        - gstin_error_code
        - gstin_Process_status
        - intg_tracking_id

          ################################ Database table details configuration ########################
# list of columns in invoice and items table. separated by comma

table-metadata-configuration:
        tables:
          -
            name: gstrTable
            identifierColumn: FIRST_PARTY_PRIMARY_REG_NUM
            columns:
              - TAX_LINE_ID                 
              - TAX_LINE_NUM                 
              - FIRST_PARTY_PRIMARY_REG_NUM  
              - FIRST_PARTY_REG_ID           
              - THIRD_PARTY_REG_NUM         
              - TRX_ID                       
              - TAX_INVOICE_NUMBER          
              - TAX_INVOICE_DATE             
              - TAX_INVOICE_VALUE            
              - TAX_RATE                     
              - TAXABLE_AMT                
              - GRAND_TOT                   
              - CUR_GT                     
              - SGST                        
              - CGST                     
              - IGST                     
              - CESS                    
              - POS                       
              - TAX_TYPE_CODE             
              - ITEM_DESCRIPTION            
              - LOCATION_ID                 
              - FLAG                      
              - INV_TYPE                   
              - REV_CHARGE                 
              - ECOM_OPERATOR               
              - INV_CHECK_SUM_VAL           
              - EXPORT_TYPE                  
              - SHIPPABLE_PORT_CODE          
              - SHIPPABLE_BILL_NO           
              - SHIPPABLE_BILL_DATE         
              - HSN_CODE                   
              - HSN_DESC                  
              - QTY                       
              - UOM                         
              - CPPDR                        
              - NIL_AMOUNT                  
              - EXPT_AMOUNT                  
              - NGSUP_AMOUNT                 
              - ADV_RECEIPT_AMT              
              - ADJUSTMENT_AMOUNT           
              - SUPP_TYPE                  
              - APPLIED_TO_TRX_ID           
              - REQUEST_ID                  
              - ATTRIBUTE1                  
              - ATTRIBUTE2                   
              - ATTRIBUTE3                   
              - ATTRIBUTE4                   
              - ATTRIBUTE5                 
              - ATTRIBUTE6                
              - ATTRIBUTE7                  
              - ATTRIBUTE8                   
              - ATTRIBUTE9                  
              - ATTRIBUTE10                 
              - ATTRIBUTE11                 
              - ATTRIBUTE12                  
              - APPLIED_FROM_TRX_ID         
              - INELIG_ITC_FLAG             
              - ITC_IGST                     
              - ITC_SGST                     
              - ITC_CGST                     
              - ITC_CESS                     
              - RULE_NO                      
              - SERIAL_NUM                   
              - PORT_CODE                    
              - IS_SEZ                       
              - REV_GSTIN                    
              - REV_INV_NUM                  
              - REV_INV_DATE                 
              - REV_INV_VAL                  
              - NOTE_TYPE                    
              - NOTE_NUMBER                  
              - NOTE_DATE                   
              - P_GST                
              - RSN                      
              - ELG                      
              - CHKSUM                     
              - TRX_NUMBER                 
              - TRX_DATE                     
              - EVENT_CLASS_CODE          
              - DOC_TYPE                 
              - TOT_NUM                    
              - CANCEL                      
              - NET_ISSUE                   
              - STATUS                      
              - ELIGIBLE_GSTR1              
              - STATUS_GSTR1                
              - ELIGIBLE_GSTR2              
              - STATUS_GSTR2                
              - PERIOD_NAME                 
              - SOURCE_SECTION              
              - BATCH_ID                     
              - PROCESS_STATUS  
####################### GSTR1 COLUMNS CONFIGURATION ####################    
gstr-table-columns:
  gstr:
    -
      name: saveGSTR
      columns:
        TAX_LINE_ID : TAX_LINE_ID                 
        TAX_LINE_NUM : TAX_LINE_NUM                
        FIRST_PARTY_PRIMARY_REG_NUM : FIRST_PARTY_PRIMARY_REG_NUM 
        FIRST_PARTY_REG_ID : FIRST_PARTY_REG_ID           
        THIRD_PARTY_REG_NUM : THIRD_PARTY_REG_NUM        
        TRX_ID : TRX_ID                       
        TAX_INVOICE_NUMBER : TAX_INVOICE_NUMBER         
        TAX_INVOICE_DATE : TAX_INVOICE_DATE            
        TAX_INVOICE_VALUE : TAX_INVOICE_VALUE            
        TAX_RATE : TAX_RATE                     
        TAXABLE_AMT : TAXABLE_AMT               
        GRAND_TOT : GRAND_TOT                   
        CUR_GT : CUR_GT                     
        SGST : SGST                       
        CGST : CGST                    
        IGST : IGST                     
        CESS : CESS                   
        POS : POS                      
        TAX_TYPE_CODE : TAX_TYPE_CODE            
        ITEM_DESCRIPTION : ITEM_DESCRIPTION            
        LOCATION_ID : LOCATION_ID                
        FLAG : FLAG                     
        INV_TYPE : INV_TYPE                  
        REV_CHARGE : REV_CHARGE                
        ECOM_OPERATOR : ECOM_OPERATOR              
        INV_CHECK_SUM_VAL : INV_CHECK_SUM_VAL           
        EXPORT_TYPE : EXPORT_TYPE                  
        SHIPPABLE_PORT_CODE : SHIPPABLE_PORT_CODE         
        SHIPPABLE_BILL_NO : SHIPPABLE_BILL_NO          
        SHIPPABLE_BILL_DATE : SHIPPABLE_BILL_DATE        
        HSN_CODE : HSN_CODE                   
        HSN_DESC : HSN_DESC                  
        QTY : QTY                      
        UOM : UOM                        
        CPPDR : CPPDR                       
        NIL_AMOUNT : NIL_AMOUNT                 
        EXPT_AMOUNT : EXPT_AMOUNT                  
        NGSUP_AMOUNT : NGSUP_AMOUNT                
        ADV_RECEIPT_AMT : ADV_RECEIPT_AMT            
        ADJUSTMENT_AMOUNT : ADJUSTMENT_AMOUNT          
        SUPP_TYPE : SUPP_TYPE                  
        APPLIED_TO_TRX_ID : APPLIED_TO_TRX_ID          
        REQUEST_ID : REQUEST_ID               
        ATTRIBUTE1 : ATTRIBUTE1                 
        ATTRIBUTE2 : ATTRIBUTE2                  
        ATTRIBUTE3 : ATTRIBUTE3                  
        ATTRIBUTE4 : ATTRIBUTE4                  
        ATTRIBUTE5 : ATTRIBUTE5                
        ATTRIBUTE6 : ATTRIBUTE6               
        ATTRIBUTE7 : ATTRIBUTE7                 
        ATTRIBUTE8 : ATTRIBUTE8                  
        ATTRIBUTE9 : ATTRIBUTE9                 
        ATTRIBUTE10 : ATTRIBUTE10                
        ATTRIBUTE11 : ATTRIBUTE11                
        ATTRIBUTE12 : ATTRIBUTE12                 
        APPLIED_FROM_TRX_ID : APPLIED_FROM_TRX_ID        
        INELIG_ITC_FLAG : INELIG_ITC_FLAG            
        ITC_IGST : ITC_IGST                     
        ITC_SGST : ITC_SGST                    
        ITC_CGST : ITC_CGST                     
        ITC_CESS : ITC_CESS                   
        RULE_NO : RULE_NO                      
        SERIAL_NUM : SERIAL_NUM                  
        PORT_CODE : PORT_CODE                    
        IS_SEZ  : IS_SEZ                      
        REV_GSTIN : REV_GSTIN                   
        REV_INV_NUM : REV_INV_NUM                 
        REV_INV_DATE : REV_INV_DATE                
        REV_INV_VAL : REV_INV_VAL                 
        NOTE_TYPE : NOTE_TYPE                    
        NOTE_NUMBER : NOTE_NUMBER                 
        NOTE_DATE : NOTE_DATE                   
        P_GST : P_GST                
        RSN : RSN                     
        ELG : ELG                   
        CHKSUM : CHKSUM                   
        TRX_NUMBER : TRX_NUMBER                 
        TRX_DATE : TRX_DATE                    
        EVENT_CLASS_CODE  : EVENT_CLASS_CODE         
        DOC_TYPE : DOC_TYPE                 
        TOT_NUM : TOT_NUM                    
        CANCEL : CANCEL                    
        NET_ISSUE : NET_ISSUE                  
        STATUS : STATUS                     
        ELIGIBLE_GSTR1 : ELIGIBLE_GSTR1             
        STATUS_GSTR1 : STATUS_GSTR1              
        ELIGIBLE_GSTR2 : ELIGIBLE_GSTR2            
        STATUS_GSTR2 : STATUS_GSTR2               
        PERIOD_NAME : PERIOD_NAME                
        SOURCE_SECTION : SOURCE_SECTION          
        BATCH_ID : BATCH_ID                    
        PROCESS_STATUS : PROCESS_STATUS
      components:
        B2B : B2B
        HSNSUM : HSNSUM
        CDNUR : CDNUR
        NIL : NIL
        CDN : CDN
        B2BUR : B2BUR
        IMPG : IMPG
        TXPD : TXPD
                           
####################### GSTR1 API CONFIGURATION ####################
api-configuration:
  apis:
    -
      name: saveGSTR
      headers:
        ocp-apim-subscription-key: 7ad84a349ab045e7a2e0f274f17a8855
        gstinno: 29AAKCA7120L1ZE
        source_type: ERP
        reference_no: WEP00531
        outputtype: json
        Content-Type: application/json
        Authorization: Basic Og==
        HTTP_METHOD: POST
      url: https://api.wepgst.com/asp/gstr2/save

audit-configuration:
  url: http://localhost:5984/gstr2tb