CREATE TABLE XXVIS_GSTR1_MAIN_TAB
(
  DETAIL_TAX_LINE_ID           NUMBER(22),
  FIRST_PARTY_PRIMARY_REG_NUM  VARCHAR2(30 BYTE),
  PERIOD_NAME                  VARCHAR2(20 BYTE),
  GROSS_TURNOVER               NUMBER,
  CURRENT_GROSS_TURNOVER       NUMBER,
  SECTION_CODE                 VARCHAR2(10 BYTE),
  THIRD_PARTY_REG_NUM          VARCHAR2(30 BYTE),
  TRX_ID                       NUMBER(22),
  TAX_INVOICE_NUMBER           VARCHAR2(150 BYTE),
  TAX_INVOICE_DATE             DATE,
  TAX_INVOICE_VALUE            NUMBER(22),
  SERIAL_NO                    NUMBER,
  TAX_RATE                     NUMBER(22),
  TAXABLE_AMT                  NUMBER(22),
  SGST                         NUMBER(22),
  CGST                         NUMBER(22),
  IGST                         NUMBER(22),
  CESS                         NUMBER(22),
  LOCATION_ID                  NUMBER(22),
  STATE                        VARCHAR2(50 BYTE),
  FLAG                         VARCHAR2(1 BYTE),
  INV_TYPE                     VARCHAR2(8 BYTE),
  REV_CHARGE                   VARCHAR2(1 BYTE),
  ECOM_OPERATOR                VARCHAR2(20 BYTE),
  INV_CHECK_SUM_VAL            VARCHAR2(20 BYTE),
  EXPORT_TYPE                  VARCHAR2(10 BYTE),
  SHIPPABLE_PORT_CODE          VARCHAR2(10 BYTE),
  SHIPPABLE_BILL_NO            VARCHAR2(15 BYTE),
  SHIPPABLE_BILL_DATE          DATE,
  HSN_CODE                     VARCHAR2(50 BYTE),
  HSN_DESC                     VARCHAR2(240 BYTE),
  QTY                          NUMBER(22),
  UOM                          VARCHAR2(10 BYTE),
  NIL_AMOUNT                   NUMBER(22),
  EXPT_AMOUNT                  NUMBER(22),
  NGSUP_AMOUNT                 NUMBER(22),
  ADV_RECEIPT_AMT              NUMBER(22),
  SUPP_TYPE                    VARCHAR2(50 BYTE),
  APPLIED_TO_TRX_ID            NUMBER(22),
  REQUEST_ID                   NUMBER(22),
  CREATED_BY                   NUMBER(22),
  CREATION_DATE                DATE,
  LAST_UPDATED_BY              NUMBER(22),
  LAST_UPDATE_DATE             DATE,
  LAST_UPDATE_LOGIN            NUMBER(22),
  ATTRIBUTE1                   VARCHAR2(200 BYTE),
  ATTRIBUTE2                   VARCHAR2(200 BYTE),
  ATTRIBUTE3                   VARCHAR2(200 BYTE),
  ATTRIBUTE4                   VARCHAR2(200 BYTE),
  ATTRIBUTE5                   VARCHAR2(200 BYTE),
  ATTRIBUTE6                   VARCHAR2(200 BYTE),
  ATTRIBUTE7                   VARCHAR2(200 BYTE),
  ATTRIBUTE8                   VARCHAR2(200 BYTE),
  ATTRIBUTE9                   VARCHAR2(200 BYTE),
  ATTRIBUTE10                  VARCHAR2(200 BYTE),
  ATTRIBUTE11                  VARCHAR2(200 BYTE),
  ATTRIBUTE12                  VARCHAR2(200 BYTE),
  APPLIED_FROM_TRX_ID          NUMBER(22),
  INELIG_ITC_FLAG              VARCHAR2(1 BYTE),
  ITC_IGST                     NUMBER(22),
  ITC_SGST                     NUMBER(22),
  ITC_CGST                     NUMBER(22),
  ITC_CESS                     NUMBER(22),
  SERIAL_NUM                   NUMBER(22),
  PORT_CODE                    NUMBER(22),
  IS_SEZ                       VARCHAR2(1 BYTE),
  REV_GSTIN                    VARCHAR2(50 BYTE),
  REV_INV_NUM                  VARCHAR2(50 BYTE),
  REV_INV_DATE                 DATE,
  REV_INV_VAL                  NUMBER(22),
  NOTE_TYPE                    VARCHAR2(50 BYTE),
  P_GST                        VARCHAR2(10 BYTE),
  RSN                          VARCHAR2(20 BYTE),
  TRX_NUMBER                   VARCHAR2(50 BYTE),
  TRX_DATE                     DATE,
  EVENT_CLASS_CODE             VARCHAR2(250 BYTE),
  ERROR_MSG_GSTR1              VARCHAR2(250 BYTE),
  ERROR_MSG_GSTR2              VARCHAR2(250 BYTE),
  ERROR_MSG_CODE1              VARCHAR2(250 BYTE),
  ERROR_MSG_CODE2              VARCHAR2(250 BYTE),
  SOURCE                       VARCHAR2(250 BYTE),
  SOURCE_APPLICATION           VARCHAR2(250 BYTE),
  PROCESS_STATUS               VARCHAR2(250 BYTE),
  BATCH_ID                     NUMBER
)
